### ISSUE TITLE
hide dropdown + icons not shown

### ISSUE THREAD

**Issue by vnijs** [yonicd/snapper#2]
Just curious if something like a short "sleep" after clicking would allow the screenshot to be created after the dropdown has been hidden (note that I'm using "body" to get the whole page). Also, any idea why the icons are not shown?

![image](https://user-images.githubusercontent.com/2998956/81256350-17ee5700-8fe5-11ea-87c2-e251f96befa1.png)

**Comment by vnijs** [comment]
FYI Adding 1 second sleep already addresses the issue. Would you consider a PR where a "sleep" argument is added to the different buttons and links? Default would  be 0 but this could be set to any value the user chooses.

Would still like to know about the icons not showing as well. 

```
cavnas_template <- '(setTimeout(function () {html2canvas($("%s")[0]%s).then(canvas=>{%s});}), 1000)();'
```

**Comment by vnijs** [comment]
Looks like there is a PR in the works at https://github.com/niklasvh/html2canvas/pull/2219

**Comment by yonicd** [comment]
i think there is a way to pass that in the config settings. see [here](https://github.com/yonicd/snapper/blob/master/R/config.R#L11)

But yeah, the PR should be a better solution...

**Comment by vnijs** [comment]
I tried `imageTimeout` but it doesn't seem to have any effect. If, instead, I replace `cavnas_template` (existing typo :) ) in build.R with the below you should not see the dropdown menu in the modal if you run my example from https://github.com/yonicd/snapper/issues/3#issuecomment-625468563. Without this line the dropdown is shown however which I don't want.

`cavnas_template <- '(setTimeout(function () {html2canvas($("%s")[0]%s).then(canvas=>{%s});}), 1000)();'`

The downside, however, is this error in the developer tools console. If we can get this to work without the error I can create the PR for the different buttons and links

![image](https://user-images.githubusercontent.com/2998956/81340686-1a909100-9065-11ea-80d5-9f7c9888d411.png)

**Comment by yonicd** [comment]
hmmm... you can also pass in elements that html2canvas [ignores](https://github.com/yonicd/snapper/blob/master/R/config.R#L13) that could also be a more natural way.

thanks for catching the typo :)

**Comment by vnijs** [comment]
The piece I'm trying to ignore (i.e., the dropdown) doesn't have a normal ID and so `ignoreElements` didn't like that. The below looks really promising, however, but I'm not sure how to add the `data-html2canvas-ignore=true` argument to a `tabPanel` in shiny

https://stackoverflow.com/a/20678947/1974918

**Comment by yonicd** [comment]
this works, you can play with the class name in the browser inspector until you find the one you want

```r
ui <- navbarPage("Snapper app",
                 navbarMenu("", icon = icon("save"),
                            tabPanel(
                              snapper::preview_link(
                                "screenshot_link", ui = "body", 
                                previewId = "screenshot_link_preview", 
                                label = "Take a screenshot",
                                opts = config(
                                  ignoreElements = "function (el) {return el.className === 'dropdown-menu';}"
                                )
                              )
                            )
                 ),
                 tags$head(
                   tags$style(HTML( "img { max-width: 85% !important; height: auto; }" )),
                   snapper::load_snapper()
                 )
)

server <- function(input, output, session) {
  observeEvent(input$screenshot_link, {
    showModal(
      modalDialog(
        title = "App screenshot",
        span(snapper::snapper_div(id = "screenshot_link_preview")),
        footer = tagList(
          snapper::download_button(
            ui = "body",
            label = "Download screenshot",
            filename = "snapper-body.png"
          ),
          modalButton("Cancel"),
        ),
        size = "m",
        easyClose = TRUE
      )
    )
  })
}

shinyApp(ui, server)

```

**Comment by vnijs** [comment]
I was able to hide the dropdown **and** remove the JS error using the setup below (i.e., 2 millisecond delay). Would you be willing to accept that as the default?

`canvas_template <- 'setTimeout(function () {html2canvas($("%s")[0]%s).then(canvas=>{%s});}, 2)'`

**Comment by yonicd** [comment]
i think the solution above is the more "right" one. 

A good vignette would be more insightful for people to know how to ignore elements.

timeout seems like a way around that should be avoided from previous experience

**Comment by vnijs** [comment]
Agreed! Had no idea you could include a JS function like that. This works great.

**Comment by yonicd** [comment]
Can this be closed?

**Comment by vnijs** [comment]
If there is no easy way to get the icons to show up other than wait for the html2canvas PR linked below to go through, then yes. Thanks

https://github.com/niklasvh/html2canvas/pull/2219

**Comment by yonicd** [comment]
Yeah. That seems like a more low level issue that snapper can’t resolve

**Comment by vnijs** [comment]
Thanks for your help @yonicd!

**Comment by jayaddison** [comment]
@yonicd @vnijs If you get the time and opportunity, I'd appreciate any critical feedback and/or verification of https://github.com/niklasvh/html2canvas/pull/2219 to make sure we can resolve that one in the best way possible.

One out-standing question is whether the fix needs to be pushed one layer deeper, from the current location in the handling of font names, to the core `html2canvas` CSS parsing code.  I'm not yet familiar enough with the codebase to say for sure, but keen to fix it properly.

**Comment by yonicd** [comment]
i'll definitely take a look when i get another chance.

**Comment by vnijs** [comment]
@jayaddison Is there an easily accessible source for html2canvas.js based on your PR you could provide perhaps? If so, I'd be happy to test this out.

**Comment by vnijs** [comment]
@jayaddison Not sure if I used npm correctly but I tried building html2canvas.js from your https://github.com/jayaddison/html2canvas/tree/font-family-tokenization branch and got the result below.

![image](https://user-images.githubusercontent.com/2998956/81438546-d2837400-9121-11ea-93d5-1826565f0a7a.png)

**Comment by jayaddison** [comment]
@vnijs Thanks for testing that out - looks like there's still some more work to do :)

If you can provide some repro details I'll have a dig into that soon - and/or feel free to run with that branch and see what you can discover.

**Comment by vnijs** [comment]
@jayaddison You would need install R (https://cloud.r-project.org/) to reproduce the issue and then run the code below. The first two lines only need to be run once.

 If you have an alternative URL for `html2canvas.js`, you would have to change the line with `snapper::load_snapper`.

```
install.packages(c("shiny", "DiagrammeR", "remotes"))
remotes::install_github("yonicd/snapper")
library(shiny)
library(DiagrammeR)
library(snapper)

ui = fluidPage(
  snapper::load_snapper("https://html2canvas.hertzen.com/dist/html2canvas.js"),
  snapper::preview_button(
    ui = '#diagram',
    opts = snapper::config(scale = 1, removeContainer = FALSE)
  ),
  DiagrammeROutput('diagram'),
  snapper::snapper_div()
)

server = function(input, output) {
  output$diagram <- renderDiagrammeR({
    mermaid("graph LR; A-->B; A-->C; C-->E; B-->D; C-->D; D-->F; E-->F")
  })
}

shinyApp(ui, server)
```

**Comment by jayaddison** [comment]
Thanks @vnijs; I haven't had time to set this up yet, but would like to.

If you have an environment ready-to-go, then you might be able to adjust the `load_snapper` `html2canvas.js` URL to point to [this static compiled version](https://raw.githubusercontent.com/jayaddison/html2canvas/6096b36634857cac7d30929c7ae923ee824879e5/dist/html2canvas.js) that I have in a branch.

**Comment by vnijs** [comment]
Thanks for following up @jayaddison! I had some issues using the link you provided for some reason (see error message below). However, when I downloaded your version to my Desktop and used `http-server` it did generate a preview. Unfortunately, the same issue pops up.

![image](https://user-images.githubusercontent.com/2998956/81993188-049d4600-95fa-11ea-94b3-9cfd589a0c63.png)


![image](https://user-images.githubusercontent.com/2998956/81992730-0dd9e300-95f9-11ea-815c-a58138c907a2.png)
