### ISSUE TITLE
open preview in modal

### ISSUE THREAD

**Issue by vnijs** [yonicd/snapper#3]
Wonderful package @yonicd! I'm trying to get the preview to show in a modal. Thought the below might work but no luck so far. Any suggestions?

If I can get this working the plan is to add some buttons to the modal to (1) download the image server-side (using shinyFiles), (2) download to the local machine, and (3) store as image in the project folder and include the screenshot in an Rmarkdown report (in Radiant). Would another screenshot need to be taken if it is already shown in the modal or could the preview be reused?

See also https://github.com/yonicd/snapper/pull/1 for `preview_link` and `download_link`.

```
snapper::preview_link("screenshot_link", ui = "body", previewId = "screenshot_link_preview", label = "Take a screenshot")
```

```
observeEvent(input$screenshot_link, {
  showModal(
    modalDialog(
      title = "Radiant screenshot",
      span(snapper::snapper_div(id = "screenshot_link_preview")),
      footer = modalButton("OK"),
      size = "l",
      easyClose = TRUE
    )
  )
})
```

**Comment by vnijs** [comment]
My mistake. This actually does work. I'll just repeat the 2nd park of my question below.

Now that I have this working the plan is to add some buttons to the modal to (1) download the image server-side (using shinyFiles), (2) download to the local machine, and (3) store as image in the project folder and include the screenshot in an Rmarkdown report (in Radiant). Would another screenshot need to be taken if it is already shown in the modal or could the preview be reused?

![image](https://user-images.githubusercontent.com/2998956/81258563-cb0d7f00-8fea-11ea-8957-aea37b190cde.png)

**Comment by yonicd** [comment]
Glad it works :)

The preview can be reused. The img object that contains the preview gets remade every time so you only see the last snap.

Although, I am not exactly following what you need snapper to do. 

Is there a smaller app that can mimic the action you want? 

If i can run it on my side i think i could help resolve the issue better.

**Comment by vnijs** [comment]
Below is a fist step towards what I have in mind. I plan to add more buttons and options  once I know how to access and download the image already shown in the modal. 

```
library(shiny)
library(snapper)

ui <- navbarPage("Snapper app",
  navbarMenu("", icon = icon("save"),
    tabPanel(
      snapper::preview_link(
        "screenshot_link", ui = "body", previewId = "screenshot_link_preview", label = "Take a screenshot"
      )
    )
  ),
  tags$head(
    tags$style(HTML( "img { max-width: 85% !important; height: auto; }" )),
    snapper::load_snapper()
  )
)

server <- function(input, output, session) {
  observeEvent(input$screenshot_link, {
    showModal(
      modalDialog(
        title = "App screenshot",
        span(snapper::snapper_div(id = "screenshot_link_preview")),
        footer = tagList(
          snapper::download_button(
            ui = "body",
            label = "Download screenshot",
            filename = "snapper-body.png"
          ),
          modalButton("Cancel"),
        ),
        size = "m",
        easyClose = TRUE
      )
    )
  })
}

shinyApp(ui, server)
```

**Comment by yonicd** [comment]
Is this issue still unresolved after the solution in https://github.com/yonicd/snapper/issues/2?

**Comment by vnijs** [comment]
If possible, I'd still like know how to download/access the preview image shown in the modal.

**Comment by yonicd** [comment]
The same preview image is a mimic of the download actions (link/button). You could just use those.

Or you could use the native shiny download action and point to the snapper div container that holds the preview.

**Comment by vnijs** [comment]
The `snapper::download_button` works. Thanks. However, when using a native shiny download action, what would be the best way to "point to the snapper div container that holds the preview"? The download handler at the bottom of the following example works fine for generated images

```
library(shiny)
library(snapper)

ui <- navbarPage("Snapper app",
  navbarMenu("", icon = icon("save"),
    tabPanel(
      snapper::preview_link(
        "screenshot_link", ui = "body", previewId = "screenshot_link_preview", label = "Take a screenshot",
        opts = config(
          ignoreElements = "function (el) {return el.className === 'dropdown-menu';}"
        )
      )
    )
  ),
  tags$head(
    tags$style(HTML( "img { max-width: 85% !important; height: auto; }" )),
    snapper::load_snapper()
  )
)

server <- function(input, output, session) {
  observeEvent(input$screenshot_link, {
    showModal(
      modalDialog(
        title = "App screenshot",
        span(snapper::snapper_div(id = "screenshot_link_preview")),
        footer = tagList(
          downloadButton("download_screenshot", "Download"),
          snapper::download_button(
            ui = "#screenshot_link_preview",
            label = "Download screenshot",
            filename = "snapper-body.png"
          ),
          modalButton("Cancel"),
        ),
        size = "m",
        easyClose = TRUE
      )
    )
  })

  # Downloadable csv of selected dataset ----
  output$download_screenshot <- downloadHandler(
    filename = function() {
      "radiant-screenshot.png"
    },
    content = function(file) {
      png(file)
      snapper::snapper_div(id = "screenshot_link_preview")
      # plot(1:10)
      dev.off()
    }
  )
}

shinyApp(ui, server)
```

**Comment by yonicd** [comment]
you are right that is a mess since the image is embedded as data in the `img` tag. 

you could write another `onclick` action but that is redundant in my opinion with what `snapper` already has available.

The user has these options currently:

  - right click + download
  - `snapper` download button
  - `snapper` download link

**Comment by vnijs** [comment]
Thanks for the comment @yonicd. `snapper` does indeed already achieve its goal. I want to (ab)use it to work with `shinyFiles` so I can save the images server-side. This would require an R function that renders the png or can access it from the temporary file location. Any chance you could point me in the right direction to work on a function like that?

**Comment by yonicd** [comment]
you can use this to get the image data

```js
$('#preview_side img').attr('src')
```

and then use `base64enc` to convert to something that R can render. 

Here are some steps from SO

https://stackoverflow.com/questions/46032969/how-to-display-base64-images-in-r

**Comment by vnijs** [comment]
Making progress. The only bit that isn't working quite right is getting the `img` into R. It does work, but only on the 2nd click, which is annoying :) I posted a question on SO and will close this issue. 

Thanks again for your help and, of course, for creating `snapper`!

https://stackoverflow.com/questions/61690502/shiny-setinputvalue-only-works-on-the-2nd-try

```
library(shiny)
# remotes::install_github("yonicd/snapper")
library(snapper)
library(base64enc)
library(png)

js <- '
Shiny.addCustomMessageHandler("get_img_src", get_img_src);

function get_img_src(message) {
  var img_src = $("#screenshot_link_preview img").attr("src");
  Shiny.setInputValue("img_src", img_src);
}
'

ui <- navbarPage("Snapper app",
  navbarMenu("", icon = icon("save"),
    tabPanel(
      snapper::preview_link(
        "screenshot_link", ui = "body", previewId = "screenshot_link_preview", label = "Take a screenshot",
        opts = config(
          ignoreElements = "function (el) {return el.className === 'dropdown-menu';}"
        )
      )
    )
  ),
  tags$head(
    tags$style(HTML("img { max-width: 85% !important; height: auto; }")),
    tags$script(HTML(js)),
    snapper::load_snapper()
  )
)

server <- function(input, output, session) {
  observeEvent(input$screenshot_link, {
    showModal(
      modalDialog(
        title = "App screenshot",
        span(snapper::snapper_div(id = "screenshot_link_preview")),
        footer = tagList(
          downloadButton("download_screenshot", "Download (shiny)"),
          snapper::download_button(
            ui = "#screenshot_link_preview",
            label = "Download (snapper)",
            filename = "snapper-body.png"
          ),
          modalButton("Cancel"),
        ),
        size = "m",
        easyClose = TRUE
      )
    )
  })

  output$download_screenshot <- downloadHandler(
    filename = function() {
      "radiant-screenshot.png"
    },
    content = function(file) {
      session$sendCustomMessage("get_img_src", "")
      plt <- sub("data:.+base64,", "", input$img_src)
      plt <- png::readPNG(base64enc::base64decode(what = plt))
      png::writePNG(plt, file)
    }
  )
}

shinyApp(ui, server)
```

**Comment by yonicd** [comment]
what do you mean second click? i clicked download (shiny), then i get a prompt and press enter. what do you want to be skipped?

**Comment by vnijs** [comment]
When you first click 'Download (shiny)', the image  download will ultimately fail. If you then click the button again the image download does succeed.

**Comment by vnijs** [comment]
FYI @yonicd I now have a fully working solution to this issue. Thanks so much for your help and for creating snapper!

https://stackoverflow.com/questions/61690502/shiny-setinputvalue-only-works-on-the-2nd-try

https://gist.github.com/vnijs/82d4a49448f8cf93e01537c5c8557200

**Comment by yonicd** [comment]
Thanks for kicking the tires and improving it!

**Comment by vnijs** [comment]
It is a great tool! One more question ... have you seen a fix for select input with multiple variables selected? The first screenshot is from `canvas2html` and the 2nd from a standard os screenshot.

![image](https://user-images.githubusercontent.com/2998956/81489732-1368af00-922e-11ea-9720-5342cf166bf0.png)

![image](https://user-images.githubusercontent.com/2998956/81489782-cd601b00-922e-11ea-84ea-0487deaf44b2.png)

**Comment by yonicd** [comment]
Haven’t seen that yet. Can you make that a new issue? Just so it will be easier to keep track of the different edge cases. Thanks

**Comment by yonicd** [comment]
Re the gist. That would make a great vignette. Do you want to create a PR for it ? ( i can make the doc too if you don’t have time for it)

**Comment by vnijs** [comment]
@yonicd I made a new issue with a reproducible example. Unfortunately, I'm (very) low on time but feel free to use the gist as an example in a vignette. Note that shinyFiles was just recently updated on CRAN so the changes to make `onclick` work will only be available through GitHub for a while.

**Comment by yonicd** [comment]
Great. Thanks for the info re shinyFiles
