### ISSUE TITLE
selectInput values not shown

### ISSUE THREAD

**Issue by vnijs** [yonicd/snapper#4]
It seems that a `selectInput` with `multiple = TRUE, selectize = FALSE` will only show a single selected variable in the sidebar. If `selectize = TRUE`,  however, all selected values are shown.

![image](https://user-images.githubusercontent.com/2998956/81507585-3c7f5300-92b3-11ea-9041-89a35b2952d5.png)

Reproducible example

```
library(shiny)
library(snapper)

ui <- fluidPage(
  load_snapper(),
  titlePanel("Select Input (multiple)"),
  sidebarLayout(
    sidebarPanel(id = "side",
      selectInput(
        "sel_mult", "Select multiple:", choices = LETTERS,
        multiple = TRUE, size = 8, selectize = FALSE
      ),
      selectInput(
        "sel_multz", "Select multiple:", choices = LETTERS,
        multiple = TRUE
      ),
      snapper::preview_button(
        ui = "#side",
        previewId = "screenshot_preview",
        label = "Take a screenshot",
      )
    ),
    mainPanel(
      shiny::tags$h3('Selected variables 1'),
      textOutput("sel_print"),
      shiny::tags$h3('Selected variables 2'),
      textOutput("sel_printz"),
      shiny::tags$h3('Screenshot preview'),
      snapper::snapper_div(id = "screenshot_preview")
    )
  )
)

server <- function(input, output) {
  output$sel_print <- renderText({
    print(input$sel_mult)
  })
  output$sel_printz <- renderText({
    print(input$sel_multz)
  })
}

shinyApp(ui, server)
```

**Comment by vnijs** [comment]
@jayaddison I was wondering if you might also have some idea about why html2canvas does not show all selected variables in the following screenshot. The html2canvas preview is the image on the right.

![image](https://user-images.githubusercontent.com/2998956/81994097-f51efc80-95fb-11ea-8a7f-f2fb8712c82d.png)

The relevant html is here:

```
<select id="sel_mult" class="form-control" size="8" multiple="multiple"><option value="A">A</option>
<option value="B">B</option>
<option value="C">C</option>
<option value="D">D</option>
<option value="E">E</option>
<option value="F">F</option>
...
```

The `form-control` class is defined in the css file linked below: 

https://github.com/rstudio/shiny/blob/b07e553b9ebed5de08da2950e4917fb5803c78f4/inst/www/shared/bootstrap/css/bootstrap.css

**Comment by vnijs** [comment]
In case this is of interest to you, I found a way to fully capture text in textAreas and all variables in multi-selects (without selectize). 

https://stackoverflow.com/questions/75576148/vertical-cropping-of-screenshot-after-applying-changes-during-onclone-html2canv

I'll close this issue.

**Comment by yonicd** [comment]
Thanks. This issue must have slipped through with the other repo issue. Apologies
