### ISSUE TITLE
Strangely does not work with some images!!!

### ISSUE THREAD

**Issue by asalavaty** [yonicd/snapper#6]
Hi Yoni,

I'm facing a really strange issue with your really cool package! I have tested other packages for taking screenshots but yours worked better than others, at least in my experience, in capturing the exact element I am selecting.

The problem is that the snapper works with some images but does NOT work properly with some others! I have spent several days figuring out what is the problem but I couldn't!

Please see below a simple reproducible example. The snapper is able to take screenshots of image1 but not image2!

I have tested several things including:
1. renaming the file
2. editing the file using photoshop and cropping a small section of that
3. Converting the image to other formats

NONE of these strategies worked! Quite strange! 

Can you please help me resolve this issue?

I have also uploaded the images below.

```
library(shiny)
library(ggplot2)
library(bs4Dash)
library(colordistance)
library(snapper)


ui = bs4DashPage(
  
  header = dashboardHeader(title = "Title"),
  
  sidebar = dashboardSidebar(),
  
  body = dashboardBody(
  
  fileInput("major_image", label = "Image",
            accept = c(".png", ".jpg", ".jpeg"),
            width = "100%",multiple = TRUE,
            buttonLabel = "Browse"),

  column(width = 4,
              
              load_snapper(),
              uiOutput(outputId = "majorImgScreenshotBtnUI"),
         
         br(), br(),
              
          plotOutput("uploaded_major_image",
             brush = brushOpts(
               id = "major_image_zoom_section",
               fill = NA,
               stroke = "white",
               opacity = 1,
               resetOnNew = TRUE
  )
          )
  )
  )
  
)

server <- function(input, output, session) {
  
major_image_file <- eventReactive(input$major_image, {
    colordistance::loadImage(path = input$major_image[['datapath']],
                             lower = c(0, 0, 0), upper = c(0.1, 0.1, 0.1),
                             hsv = TRUE, alpha.channel = FALSE)
  })
  
  major_image_rgb <- reactive({
    major_image_file()$original.rgb
    
  })
  
  
  output$uploaded_major_image <- renderPlot({
    ggplot() +
      annotation_custom(rasterGrob(major_image_rgb(),
                                   width = unit(1,"npc"),
                                   height = unit(1,"npc")),
                        -Inf, Inf, -Inf, Inf) +
      theme_void()
  })
  
  output$majorImgScreenshotBtnUI <- renderUI({
      snapper::download_button(ui = '#uploaded_major_image',
                            label = 'Approve Section', 
                            filename = paste0(input$major_image[['name']], ".png"))
  })
  
  
}

shinyApp(ui = ui, server = server)
```

![1](https://user-images.githubusercontent.com/15263329/131439300-b44a0a05-006a-4287-83eb-98f3a550b39b.png)

![2](https://user-images.githubusercontent.com/15263329/131439292-1638823b-35a1-4e8e-8e0e-eabde8d1415b.png)

**Comment by yonicd** [comment]
Thanks for trying out the package. I’ll test out the images and get back to you

**Comment by yonicd** [comment]
Can you explain what the steps in the app are supposed to be and what the desired result is supposed to be.

I can load the app with the images and if I select a part of the image and click on approve selection then the whole image is saved.

**Comment by asalavaty** [comment]
> Can you explain what the steps in the app are supposed to be and what the desired result is supposed to be.
> 
> I can load the app with the images and if I select a part of the image and click on approve selection then the whole image is saved.

I am trying to make a screenshot of the images after clicking on the Approve button. But, as I explained above, the problem is that the snapper works with some images (e.g. Image 1) but does not work properly with some others!

Please have a look at the screen recorded video attached.

Again, as I said, I have tested several things including:

- renaming the file
- editing the file using photoshop and cropping a small section of that
- Converting the image to other formats

none of these strategies worked! Quite strange!

https://user-images.githubusercontent.com/15263329/131765557-e6e36bff-1abd-4353-8628-9fe5a4369285.mp4

**Comment by asalavaty** [comment]
> > Can you explain what the steps in the app are supposed to be and what the desired result is supposed to be.
> > I can load the app with the images and if I select a part of the image and click on approve selection then the whole image is saved.
> 
> I am trying to make a screenshot of the images after clicking on the Approve button. But, as I explained above, the problem is that the snapper works with some images (e.g. Image 1) but does not work properly with some others!
> 
> Please have a look at the screen recorded video attached.
> 
> Again, as I said, I have tested several things including:
> 
> * renaming the file
> * editing the file using photoshop and cropping a small section of that
> * Converting the image to other formats
> 
> none of these strategies worked! Quite strange!
> 
>  Snapper.mp4

By the way, I am using MAC, not sure if this is relevant to the issue.

**Comment by yonicd** [comment]
I am not experiencing this problem of some images working and some not.

What is your `sessioninfo::sessioninfo()`? which browser/version are you using when running the app?

I changed your app a bit to infer what part of the image the user wants to save using the airbrush.

```r
library(shiny)
library(ggplot2)
library(bs4Dash)
library(colordistance)
library(snapper)

ui = bs4DashPage(
  
  header = dashboardHeader(title = "Title"),
  
  sidebar = dashboardSidebar(),
  
  body = dashboardBody(
    
    fileInput("major_image", label = "Image",
              accept = c(".png", ".jpg", ".jpeg"),
              width = "100%",multiple = TRUE,
              buttonLabel = "Browse"),
    
    column(width = 4,
           
           load_snapper(),
           uiOutput(outputId = "majorImgScreenshotBtnUI"),
           
           br(), br(),
           
           plotOutput("uploaded_major_image",
                      brush = brushOpts(
                        id = "major_image_zoom_section",
                        fill = NA,
                        stroke = "white",
                        opacity = 1,
                        resetOnNew = TRUE
                      )
           ),
           snapper::snapper_div()
    )
  )
  
)

server <- function(input, output, session) {
  
  major_image_file <- eventReactive(input$major_image, {
    colordistance::loadImage(path = input$major_image[['datapath']],
                             lower = c(0, 0, 0), upper = c(0.1, 0.1, 0.1),
                             hsv = TRUE, alpha.channel = FALSE)
  })
  
  major_image_rgb <- reactive({
    major_image_file()$original.rgb
    
  })
  
  
  output$uploaded_major_image <- renderPlot({
    ggplot() +
      annotation_custom(grid::rasterGrob(major_image_rgb(),
                                   width = unit(1,"npc"),
                                   height = unit(1,"npc")),
                        -Inf, Inf, -Inf, Inf) +
      theme_void()
  })
  
  output$majorImgScreenshotBtnUI <- renderUI({
    shiny::req(input$major_image_zoom_section)
    snapper::download_button(ui = '#uploaded_major_image',
                             label = 'Approve Section',
                            opts = snapper::config(
                              x = input$major_image_zoom_section$coords_css$xmin, 
                              y = input$major_image_zoom_section$coords_css$ymin,
                              height = input$major_image_zoom_section$coords_css$ymax - input$major_image_zoom_section$coords_css$ymin,
                              width = input$major_image_zoom_section$coords_css$xmax - input$major_image_zoom_section$coords_css$xmin
                            ),
                             filename = paste0(input$major_image[['name']], ".png")
                            )
  })
  
  
}

shinyApp(ui = ui, server = server)

```

**Comment by asalavaty** [comment]
> I am not experiencing this problem of some images working and some not.
> 
> What is your `sessioninfo::sessioninfo()`? which browser/version are you using when running the app?
> 
> I changed your app a bit to infer what part of the image the user wants to save using the airbrush.
> 
> ```r
> library(shiny)
> library(ggplot2)
> library(bs4Dash)
> library(colordistance)
> library(snapper)
> 
> ui = bs4DashPage(
>   
>   header = dashboardHeader(title = "Title"),
>   
>   sidebar = dashboardSidebar(),
>   
>   body = dashboardBody(
>     
>     fileInput("major_image", label = "Image",
>               accept = c(".png", ".jpg", ".jpeg"),
>               width = "100%",multiple = TRUE,
>               buttonLabel = "Browse"),
>     
>     column(width = 4,
>            
>            load_snapper(),
>            uiOutput(outputId = "majorImgScreenshotBtnUI"),
>            
>            br(), br(),
>            
>            plotOutput("uploaded_major_image",
>                       brush = brushOpts(
>                         id = "major_image_zoom_section",
>                         fill = NA,
>                         stroke = "white",
>                         opacity = 1,
>                         resetOnNew = TRUE
>                       )
>            ),
>            snapper::snapper_div()
>     )
>   )
>   
> )
> 
> server <- function(input, output, session) {
>   
>   major_image_file <- eventReactive(input$major_image, {
>     colordistance::loadImage(path = input$major_image[['datapath']],
>                              lower = c(0, 0, 0), upper = c(0.1, 0.1, 0.1),
>                              hsv = TRUE, alpha.channel = FALSE)
>   })
>   
>   major_image_rgb <- reactive({
>     major_image_file()$original.rgb
>     
>   })
>   
>   
>   output$uploaded_major_image <- renderPlot({
>     ggplot() +
>       annotation_custom(grid::rasterGrob(major_image_rgb(),
>                                    width = unit(1,"npc"),
>                                    height = unit(1,"npc")),
>                         -Inf, Inf, -Inf, Inf) +
>       theme_void()
>   })
>   
>   output$majorImgScreenshotBtnUI <- renderUI({
>     shiny::req(input$major_image_zoom_section)
>     snapper::download_button(ui = '#uploaded_major_image',
>                              label = 'Approve Section',
>                             opts = snapper::config(
>                               x = input$major_image_zoom_section$coords_css$xmin, 
>                               y = input$major_image_zoom_section$coords_css$ymin,
>                               height = input$major_image_zoom_section$coords_css$ymax - input$major_image_zoom_section$coords_css$ymin,
>                               width = input$major_image_zoom_section$coords_css$xmax - input$major_image_zoom_section$coords_css$xmin
>                             ),
>                              filename = paste0(input$major_image[['name']], ".png")
>                             )
>   })
>   
>   
> }
> 
> shinyApp(ui = ui, server = server)
> ```

**My session info**:
```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_AU.UTF-8                 
 ctype    en_AU.UTF-8                 
 tz       Australia/Melbourne         
 date     2021-09-02  
```

**which browser/version are you using when running the app?**
I use the default RStudio to run the app. I have also tested the snapper and app on Chrome. The same results.

Thanks for changing the app code. I tested your changes. The following happens with different options set in the server:
1. If you **do NOT define the section size** in the _snapper::config_, you cannot take a screenshot of the image.
2. If you set the **section size to the full size of the image** in the _snapper::config_, you cannot take a screenshot of the image as well.
3. But, If you **define the section size** in the _snapper::config_ **according to the brushed section**, you CAN take a screenshot of the selected section.

Please have a look at the recorded video below.

https://user-images.githubusercontent.com/15263329/131771177-faca6b18-66fb-490e-ba0f-1b90ea01f5cb.mp4

I have also put the revised code below.
```
library(shiny)
library(ggplot2)
library(bs4Dash)
library(colordistance)
library(snapper)

ui = bs4DashPage(
  
  header = dashboardHeader(title = "Title"),
  
  sidebar = dashboardSidebar(),
  
  body = dashboardBody(
    
    fileInput("major_image", label = "Image",
              accept = c(".png", ".jpg", ".jpeg"),
              width = "100%",multiple = TRUE,
              buttonLabel = "Browse"),
    
    column(width = 4,
           
           load_snapper(),
           uiOutput(outputId = "majorImgScreenshotBtnUI"),
           
           br(), br(),
           
           plotOutput("uploaded_major_image",
                      brush = brushOpts(
                        id = "major_image_zoom_section",
                        fill = NA,
                        stroke = "white",
                        opacity = 1,
                        resetOnNew = TRUE
                      )
           ),
           snapper::snapper_div()
    )
  )
  
)

server <- function(input, output, session) {
  
  major_image_file <- eventReactive(input$major_image, {
    colordistance::loadImage(path = input$major_image[['datapath']],
                             lower = c(0, 0, 0), upper = c(0.1, 0.1, 0.1),
                             hsv = TRUE, alpha.channel = FALSE)
  })
  
  major_image_rgb <- reactive({
    major_image_file()$original.rgb
    
  })
  
  
  output$uploaded_major_image <- renderPlot({
    ggplot() +
      annotation_custom(grid::rasterGrob(major_image_rgb(),
                                         width = unit(1,"npc"),
                                         height = unit(1,"npc")),
                        -Inf, Inf, -Inf, Inf) +
      theme_void()
  })
  
  observe({
    if(!is.null(input$major_image_zoom_section)) {
print(c(      input$major_image_zoom_section$coords_css$ymax,
      input$major_image_zoom_section$coords_css$xmax,
      input$major_image_zoom_section$coords_css$ymin,
      input$major_image_zoom_section$coords_css$xmin))
    }
  })
  
  # Defining the width and height of the image
  majorImage_dim <- reactive({
    dim(major_image_rgb())[c(1,2)]
  })
  
  output$majorImgScreenshotBtnUI <- renderUI({
    # shiny::req(input$major_image_zoom_section)
    snapper::download_button(ui = '#uploaded_major_image',
                             label = 'Approve Section',
                             
                             # The entire image
                             # Let's select the entire image section for taking screenshot
                             # opts = snapper::config(
                             #   x = 1,
                             #   y = 1,
                             #   height = as.numeric(majorImage_dim()[1]),
                             #   width = as.numeric(majorImage_dim()[2]),
                             # ),
                             
                             # selected section of the image
                             # Now let's take the screenshot of the selected section
                             # opts = snapper::config(
                             #   x = as.numeric(input$major_image_zoom_section$coords_css$xmin),
                             #   y = as.numeric(input$major_image_zoom_section$coords_css$ymin),
                             #   height = as.numeric(input$major_image_zoom_section$coords_css$ymax - input$major_image_zoom_section$coords_css$ymin),
                             #   width = as.numeric(input$major_image_zoom_section$coords_css$xmax - input$major_image_zoom_section$coords_css$xmin)
                             # ),
                             
                             filename = paste0(input$major_image[['name']], ".png")
    )
  })
  
  
}

shinyApp(ui = ui, server = server)
```

**Comment by asalavaty** [comment]
I forgot to say that I would like to take a screenshot of the entire image while showing the white rectangle of the selected section.

**Comment by asalavaty** [comment]
First of all, thanks for spending time resolving the issue.

Just another question! You added the following chunk of code to take the screenshot of the selected section.
```
opts = snapper::config(
                              x = input$major_image_zoom_section$coords_css$xmin, 
                              y = input$major_image_zoom_section$coords_css$ymin,
                              height = input$major_image_zoom_section$coords_css$ymax - input$major_image_zoom_section$coords_css$ymin,
                              width = input$major_image_zoom_section$coords_css$xmax - input$major_image_zoom_section$coords_css$xmin
                            )
```
And the default download button sends a request to the user for saving the selected section. But, I am just wondering is it possible to add an additional _call_contents_ to the package for saving the selected section directly and automatically on the Host/server without sending any download request to the end-user?

It would be super great if this is something doable.

**Comment by yonicd** [comment]
I am not sure I am following the idea. The user would still need to inform the app that a screenshot needs to be taken, so you cant get around using a button. In such a case you could use preview_button in snapper and some JS (onclick) to copy the snapper_div contents into storage.

**Comment by asalavaty** [comment]
Thanks. It would be great. I am specifically looking for storing the screenshot of the image section on the server upon clicking on the button.

Can you please make a simple example of how to use the preview_button and the JS (onclick) to copy the snapper_div contents into app storage? For example, after clicking on the Approve section (of the above app I posted earlier), the section gets saved as a PNG file on the app storage.

**Comment by yonicd** [comment]
i think i found the problem in the app. if i observe the name of the file that is read in from fileInput it already has an extension on it. 

```r
  observe({
    req(input$major_image)
      print(c(input$major_image[['name']]))
  })
```

When you save it you are adding the extension again.

```r
filename = paste0(input$major_image[['name']], ".png")
```

If i remove that then the app works fine

```r
filename = input$major_image[['name']]
```

You can see it captures the window of the brush in the snapshot.

![img_b2](https://user-images.githubusercontent.com/1755487/131994830-f4d44233-874a-47ad-b19b-21507c0be037.png)

**Comment by yonicd** [comment]
>Can you please make a simple example of how to use the preview_button and the JS (onclick) to copy the snapper_div contents into app storage? For example, after clicking on the Approve section (of the above app I posted earlier), the section gets saved as a PNG file on the app storage.

I will show you the building blocks to create such an extension, I do not have the resources at the moment to fully implement it.

This is the code for the preview button

```r
preview_button <- function(inputId = 'btn-Preview-Image',
                           label = 'Preview',
                           ui = "#html-content-holder",
                           previewId = 'previewImage',
                           opts = config()){

  shiny::actionButton(
    inputId = inputId,
    label = label,
    onclick = build_call(
      type = 'preview',
      arg = previewId,
      opts = opts,
      ui = ui
    )
  )
}
```

notice the build_call function that is called onclick.

```r
snapper:::call_contents <- function(type = c('preview','download'),arg){

  switch(type,
         'preview' = {
           sprintf('var img = document.createElement("img");
                    img.src = canvas.toDataURL("png");
                    img.width = parseInt(canvas.style.width);
                    img.height = parseInt(canvas.style.height);
                    $("#%s").empty();
                    $("#%s").append(img);',
                   arg,arg)
         },
         'download' = {
           sprintf('saveAs(canvas.toDataURL("png"), "%s");',arg)
         })

}
```

you can add a new element to the switch call, eg `'storage'`, and write the JS needed to store the canvas to a different location.

you can use {plumber} to route the contents via an API to the server you want.

**Comment by asalavaty** [comment]
> i think i found the problem in the app. if i observe the name of the file that is read in from fileInput it already has an extension on it.
> 
> ```r
>   observe({
>     req(input$major_image)
>       print(c(input$major_image[['name']]))
>   })
> ```
> 
> When you save it you are adding the extension again.
> 
> ```r
> filename = paste0(input$major_image[['name']], ".png")
> ```
> 
> If i remove that then the app works fine
> 
> ```r
> filename = input$major_image[['name']]
> ```
> 
> You can see it captures the window of the brush in the snapshot.
> 
> ![img_b2](https://user-images.githubusercontent.com/1755487/131994830-f4d44233-874a-47ad-b19b-21507c0be037.png)

Thanks Yoni. A very nice catch! The problem was the file extension. But, it is not required to remove the extension! If you add a space before `.png` it would work as well! Not sure why!

**Comment by asalavaty** [comment]
> > Can you please make a simple example of how to use the preview_button and the JS (onclick) to copy the snapper_div contents into app storage? For example, after clicking on the Approve section (of the above app I posted earlier), the section gets saved as a PNG file on the app storage.
> 
> I will show you the building blocks to create such an extension, I do not have the resources at the moment to fully implement it.
> 
> This is the code for the preview button
> 
> ```r
> preview_button <- function(inputId = 'btn-Preview-Image',
>                            label = 'Preview',
>                            ui = "#html-content-holder",
>                            previewId = 'previewImage',
>                            opts = config()){
> 
>   shiny::actionButton(
>     inputId = inputId,
>     label = label,
>     onclick = build_call(
>       type = 'preview',
>       arg = previewId,
>       opts = opts,
>       ui = ui
>     )
>   )
> }
> ```
> 
> notice the build_call function that is called onclick.
> 
> ```r
> snapper:::call_contents <- function(type = c('preview','download'),arg){
> 
>   switch(type,
>          'preview' = {
>            sprintf('var img = document.createElement("img");
>                     img.src = canvas.toDataURL("png");
>                     img.width = parseInt(canvas.style.width);
>                     img.height = parseInt(canvas.style.height);
>                     $("#%s").empty();
>                     $("#%s").append(img);',
>                    arg,arg)
>          },
>          'download' = {
>            sprintf('saveAs(canvas.toDataURL("png"), "%s");',arg)
>          })
> 
> }
> ```
> 
> you can add a new element to the switch call, eg `'storage'`, and write the JS needed to store the canvas to a different location.
> 
> you can use {plumber} to route the contents via an API to the server you want.

Thanks for the suggestions. I had had a look at the preview_button, download_button, and call_contents functions before and tried to create a new switch type for storing the image to the host (e.g. to the www directory of the shiny app). However, I am not familiar with JS and couldn't properly implement this. I did a lot of research on the internet and I believe there are several options to achieve this but I couldn't figure out how to make the JS working with the build_call and call_contents. Please have a look at the following two URLs describing procedures to store the canvas image to the server.

https://www.kubilayerdogan.net/html2canvas-take-screenshot-of-web-page-and-save-it-to-server-javascript-and-php/

https://coursesweb.net/javascript/html2canvas-save-page-screenshoot-server

Can you please help me implement this idea, whenever you get some free time?
Thanks in advance,
Adrian

**Comment by yonicd** [comment]
Glad the images can be saved locally now. 

Using PHP is out of scope for this package and my expertise.

Best of luck
