### ISSUE TITLE
save png to server

### ISSUE THREAD

**Issue by stevepowell99** [yonicd/snapper#7]
Thanks for the useful package, it works well converting SVG output which other packages don't manage.
However I am wondering if it is possible to get at the underlying functions rather than having to use buttons to generate the images and having the image created in a preview pane. Ideally I would like just to be able to call `snapper::create_data_png()` which could then generate a preview div (which I personally don't need) or to optionally save the png to server (which is what I want). 

This works fine for me (I am using DiagrammeR for the svg output), but a) I would rather not have to press a button, I would like to be under the control of the app, and b) I would like to be able to save the data png as a png file server-side.
```
library(snapper)
library(DiagrammeR)

server <- function(input, output) {
  output$grr <- renderGrViz(grViz( "digraph test{
A🧪;
B;
A🧪 -> B;}" )
  )
}
ui <- fluidPage(id = 'page',
load_snapper(),
snapper::preview_button(ui = '#grr',   previewId = 'preview_main'),
                  div(id = 'main',
                            grVizOutput("grr", width = "100%", height = "90vh"),
                            snapper::snapper_div(id = 'preview_main')
                  )
                
)
shinyApp(ui, server)
```

**Comment by yonicd** [comment]
thanks for opening the issue. i think you would need to separate out the call [here](https://github.com/yonicd/snapper/blob/master/R/build.R#L24) to isolate `canvas.toDataURL("png")` to make things run server side and wrap it in a callback that is app driven.

**Comment by stevepowell99** [comment]
We'd really like this feature and I can't work out how to do it. Is it possible to sponsor this feature / pay to have it implemented?

**Comment by yonicd** [comment]
I am currently overstretched to get to this, I will try to find someone who can help or when I get more time I can add this feature.

cc @daattali

**Comment by daattali** [comment]
@stevepowell99 I can look into this

**Comment by yonicd** [comment]
@stevepowell99 PR https://github.com/yonicd/snapper/pull/8 should resolve your issue. thank you @daattali

**Comment by stevepowell99** [comment]
awesome
