### ISSUE TITLE
push to CRAN?

### ISSUE THREAD

**Issue by vnijs** [yonicd/snapper#9]
@yonicd I would like to push updated versions of a few of my packages to CRAN that rely on snapper. I think students will really appreciate the screenshot functionality that snapper offers. Would you consider pushing snapper to CRAN?

**Comment by yonicd** [comment]
Sure, I can do that.

**Comment by vnijs** [comment]
Thanks @yonicd. FYI I just found that I can get by with just including `html2canvas` as an htmlDependency so this is not urgent
